### PR TITLE
Correct casing of NuGet

### PR DESCRIPTION
**Pull request by Martin4ndersen**
* Correct casing of NuGet in README.md
* Correct casing of NuGet in template

image

PS. CLA is signed.

### CODE REVIEW

**Comment by mlorbetske** [comment]
@dotnet-bot test Linux x64 Release Build please
@dotnet-bot test Ubuntu x64 Release Build please
@dotnet-bot test Ubuntu16.04 x64 Debug Build please
@dotnet-bot test Ubuntu16.10 x64 Debug Build please

**Comment by dnfgituser** [comment]
Hi, I am closing and re-opening this PR to bump the CLA bot. Sorry for the inconvenience!

**Comment by seancpeters** [comment]
@dotnet-bot test Ubuntu x64 Release Build please
@dotnet-bot test Ubuntu16.04 x64 Debug Build please
@dotnet-bot test Ubuntu16.10 x64 Debug Build please

**Comment by mlorbetske** [comment]
@dotnet-bot test Ubuntu16.04 x64 Debug Build please
@dotnet-bot test Ubuntu16.10 x64 Debug Build please

**Pull request merged**
