### PR TITLE
update branding to preview5

### PR DESCRIPTION
**Pull request by Anipik**
cc @mmitche

### CODE REVIEW

**Comment by grinrag** [comment]
@Anipik do we need to create a `release/5.0-preview4` branch first?

**Comment by Anipik** [comment]
> @Anipik do we need to create a release/5.0-preview4 branch first?

yes i created one for internal, i tried that yesterday. but i dont have correct permissions, can you help me with that

**Comment by Anipik** [comment]
the preview 4 branch has been created we can merge this one

**Comment by Anipik** [comment]
merging this one as preview4 branch has been created and commit message has been updated.

**Pull request merged**
