### PR TITLE
TestPlatform 15.7 preview 1 template changes

### PR DESCRIPTION
**Pull request by abhishkk**
Release notes [here](https://github.com/Microsoft/vstest-docs/blob/master/docs/releases.md#1570-preview-20180221-13).
VS insertion PR [here](https://devdiv.visualstudio.com/DevDiv/Automated%20Testing/_git/VS/pullrequest/107873?_a=overview).
Dot net CLI PR [here](https://github.com/dotnet/cli/pull/8684).

@mlorbetske Is release/2.1 right branch for VS 15.7 preview 1?
Also, Is there any other branch in which I need to port these changes?

### CODE REVIEW

**Comment by mlorbetske** [comment]
The appropriate branch for content changes is always the active dev branch (in this case rel/2.1.0-preview2), content changes from there will flow to master and the current release branch. For the 2.1 runtime carrying CLI, these changes will flow automatically, however, for the 2.0 and 1.x runtime carrying CLIs, there'll need to be insertions of the templates into that branch after the build of the content packages becomes available.

I'll retarget these changes to rel/2.1.0-preview2.

@seancpeters when we have a green PR build, please merge rel/2.1.0-preview2 to the master and release/2.1 branches. After we have a good build, please insert the test templates into the CLI's release/2.1.2xx branch.

@livarcocc what branch of CLI should changes for the 1.x test templates go in to for 15.7 preview 1? Also, from the mail thread, are there branches for the 2.0 and 1.x runtime carrying CLIs for 15.6 where we could insert the appropriate test templates as well?

**Comment by abhishkk** [comment]
@mlorbetske Even after re-targeting to rel/2.1.0-preview2, PR contains my changes only.

**Comment by mlorbetske** [comment]
@abhishkk I see 5 other commits listed, it’d be nice if it only had the one

**Comment by abhishkk** [comment]
New [PR](https://github.com/dotnet/templating/pull/1433) targeting rel/2.1.0-preview2.

**Pull request closed without merging**
