### PR TITLE
Fixing out of support TFM in restore shim

### LINKED ISSUE #2627: dotnet new install is causing out of support error messages
Using .NET 5 RC2 SDK;

`dotnet new -i TimHeuer.GitHubActions.Templates`

Observe that a restore happens and an error message shows:
`C:\Program Files\dotnet\sdk\5.0.100-rc.2.20479.15\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.EolTargetFrameworks.targets(28,5): warning NETSDK1138: The target framework 'netcoreapp1.0' is out of support and will not receive security updates in the future. Please refer to https://aka.ms/dotnet-core-support for more information about the support policy. [C:\Users\timheuer\.templateengine\dotnetcli\v5.0.100-rc.2.20479.15\scratch\restore.csproj]`

This is due to: https://github.com/dotnet/templating/blob/633dff0b4bc05682536941936379f4dff4531c7e/src/Microsoft.TemplateEngine.Cli/Installer.cs#L236 using an out-of-support TFM for the temporary project being used to shim restore as install method.

This should be changed to at least a supported TFM.

### PR DESCRIPTION
**Pull request by timheuer**
Fixes #2627 but changing to the latest LTS.

### CODE REVIEW

**Review by bozturkMSFT — APPROVED** [review]
@dotnet/templating-engine-maintainers We should probably extract the version into a constant at some point and add some tests to act as reminders.

**Comment by vlada-shubina** [comment]
@timheuer should 5.0 branch also be patched? do we still have time to include it to 5.0 GA?

**Review by vlada-shubina — APPROVED** [review]

**Comment by timheuer** [comment]
@vlada-shubina I don't think I would block GA for this fix.  If there is a natural flow to get it in for 5.0 GA, then I'd do it, but I wouldn't do anything natural and just make sure it hits the next release train.  We should note it as a known issue though.

**Review by AR-May — APPROVED** [review]

**Comment by vlada-shubina** [comment]
> @dotnet/templating-engine-maintainers We should probably extract the version into a constant at some point and add some tests to act as reminders.

**Pull request merged**
