### PR TITLE
Remove spurious AuthenicatorUriFormat

### PR DESCRIPTION
**Pull request by benaadams**
This is actually for the `EnableAuthenticatorModel` not the `TwoFactorAuthenticationModel `

### CODE REVIEW

**Comment by mlorbetske** [comment]
@dotnet-bot test CentOS7.1 x64 Debug Build please

**Comment by mlorbetske** [comment]
LGTM, @danroth27 ?

**Comment by mlorbetske** [comment]
Ping @blowdart @danroth27 ?

**Comment by blowdart** [comment]
:shipit:

**Comment by danroth27** [comment]
:shipit:

**Pull request merged**
