### PR TITLE
Set tailcalls to true in project file

### PR DESCRIPTION
**Pull request by rodrigovidal**

### CODE REVIEW

**Comment by mlorbetske** [comment]
@enricosada @KevinRansom any thoughts on this change?

**Comment by mlorbetske** [comment]
@enricosada @KevinRansom friendly ping

**Comment by KevinRansom** [comment]
Hi @rodrigovidal,

This is already taken care of here:  the latest builds of the dotnet/cli and netsdk should have this change.

https://github.com/Microsoft/visualfsharp/blob/master/src/fsharp/FSharp.Build/Microsoft.FSharp.NetSdk.props#L40

This file deploys with compiler, because it sets values that are generally applicable.

@mlorbetske 
This PR should be closed.

Kevin

**Comment by mlorbetske** [comment]
Thanks!

**Pull request closed without merging**
