### PR TITLE
Remove ASP.NET templates because they have moved to aspnet/templating

### PR DESCRIPTION
**Pull request by SteveSandersonMS**

### CODE REVIEW

**Comment by SteveSandersonMS** [comment]
@dotnet-bot test CentOS7.1 x64 Debug Build
@dotnet-bot test RHEL7.2 x64 Release Build 
@dotnet-bot test Ubuntu x64 Release Build 
@dotnet-bot test Ubuntu16.04 x64 Debug Build

**Comment by SteveSandersonMS** [comment]
@dotnet-bot test RHEL7.2 x64 Release Build

**Comment by SteveSandersonMS** [comment]
Requesting review from @mlorbetske/@seancpeters

(For some reason, GitHub isn't offering me the option to use the native "request review" feature on this repo.)

**Comment by SteveSandersonMS** [comment]
@dotnet-bot test CentOS7.1 x64 Debug Build

**Comment by SteveSandersonMS** [comment]
@seancpeters:

> For now, if you could add the line "skip": true to each of the *.json test files

Done

**Comment by SteveSandersonMS** [comment]
@dotnet-bot test CentOS7.1 x64 Debug Build
@dotnet-bot test Linux x64 Release Build
@dotnet-bot test Ubuntu16.04 x64 Debug Build

**Comment by SteveSandersonMS** [comment]
@dotnet-bot test CentOS7.1 x64 Debug Build

**Comment by SteveSandersonMS** [comment]
@seancpeters OK to merge?

**Comment by seancpeters** [comment]
@steve - looks good to merge. Just wondering, how did you get the changes made to add "skip" to those tests, without a second commit?

**Comment by SteveSandersonMS** [comment]
@seancpeters I don't have write access to this repo, so I can't merge it. Could you please do the merge?

> Just wondering, how did you get the changes made to add "skip" to those tests, without a second commit?

Using [git rebase](https://robots.thoughtbot.com/git-interactive-rebase-squash-amend-rewriting-history). In general I try to ensure PRs are squashed down to one coherent commit representing a self-contained change before they are merged.

**Pull request merged**
