### PR TITLE
Azure AD template changes

### PR DESCRIPTION
**Pull request by HaoK**
Will go in after https://github.com/dotnet/templating/pull/898

@mlorbetske @danroth27 @javiercn

### CODE REVIEW

**Comment by mlorbetske** [comment]
Not sure if this is ready but it appears some conflicts have been introduced

**Comment by HaoK** [comment]
Yeah not ready until I merge/rebase ontop of the other PR.

**Comment by HaoK** [comment]
Removed WIP label, rebased @danroth27 your script runs clean on this PR now, take a look and if it looks good to you we should merge this, and do one final run verification using your machine against a clean (not my local) feed

**Comment by mlorbetske** [comment]
@dotnet-bot test Linux x64 Release Build please
@dotnet-bot test Ubuntu x64 Release Build please

**Pull request merged**
