### PR TITLE
Add net6.0 project templates

### PR DESCRIPTION
**Pull request by ViktorHofer**
cc @dsplaisted @mmitche

### CODE REVIEW

**Comment by vlada-shubina** [comment]
@ViktorHofer do we need to maintain other versions of templates in master (future release/6.0 branch)?  
We also have 1.x, 2.0, 2.1, 2.2., 3.0, 3.1, 5.0 templates. All these packages are marked as shippable and got updated at Nuget.org also with preview releases.
Should we keep < 3.1 in release/3.1? 5.0 in release/5.0 and only 6.0 in current master?

**Comment by ViktorHofer** [comment]
I can't speak to that as I'm don't know much about the templating infrastructure. @mmitche @wli3 do you know?

**Comment by mmitche** [comment]
I think it's mainly up to you. If you're maintain them all in the .net 6 branch, and also in the 5.0 branch, would they end up differing between the 5.0 and 6.0 branch?

**Comment by vlada-shubina** [comment]
@mmitche I doubt if Microsoft.DotNet.Common.ProjectTemplates.5.0 for 5.0 and Microsoft.DotNet.Common.ProjectTemplates.5.0 for 6.0 will be ever different. @KathleenDollard what do you think?

If I understand correctly the version of template that is shipped with SDK is the following:
- SDK 5.0  Microsoft.DotNet.Common.ProjectTemplates.5.0 (from release\5.0 branch)
- SDK 3.1  Microsoft.DotNet.Common.ProjectTemplates.3.1 (from release\3.1 branch)
- SDK 2.1  Microsoft.DotNet.Common.ProjectTemplates.2.1 (from release\2.1 branch)

I think it makes sense to keep them as following:
|branch|template package|
|-|-|
|release\2.1|Microsoft.DotNet.Common.ProjectTemplates.2.1 and below|
|release\3.1|Microsoft.DotNet.Common.ProjectTemplates.3.1, Microsoft.DotNet.Common.ProjectTemplates.3.0, Microsoft.DotNet.Common.ProjectTemplates.2.2|
|release\5.0|Microsoft.DotNet.Common.ProjectTemplates.5.0|
|master|Microsoft.DotNet.Common.ProjectTemplates.6.0|

As for shipment of templates packages to Nuget, currently we got an issue with that when releasing 5.0: 
- release/5.0 has the following templates: 1.x, 2.0, 2.1, 2.2., 3.0, 3.1, 5.0, all of them marked as shippable to NuGet. When 5.0 rc.1 was released, 1.x, 2.0, 2.1, 2.2., 3.0, 3.1 packages on NuGet were updated to include pre-release version of 5.0 which is very confusing.  We would like to avoid that, and have only version that matches upcoming runtime release as pre-release. (you can check https://www.nuget.org/packages/Microsoft.DotNet.Common.ProjectTemplates.3.1 as the example)

Also, as for earlier discussion with @KathleenDollard is there any way to stop shipping templates packages with servicing releases? Ideally we want to ship X version of templates only once with runtime release (for example Microsoft.DotNet.Common.ProjectTemplates.5.0 with 5.0 release) and then ship template only if they differ from previous version (which is not the case for most (if not all) servicing releases). I believe this case would be so rare, so manual interaction is ok for that.

**Comment by wli3** [comment]
Note, we don't have automation to insert multiple branches to multiple branches. So if all templates are in release/5.0, the automation could insert all versions to release/5.0.1xx SDK. However, there is no automation to insert release/5.0 and release/3.1 to release/5.0.1xx. You need to manually update release/3.1's template version in release/5.0.1xx.

> then ship template only if they differ from previous version

On technical side, someone need to remember when there is an actual change. Which people often forget

**Comment by vlada-shubina** [comment]
@wli3 thanks for reply.
Could you please confirm which Microsoft.DotNet.Common.ProjectTemplates are inserted to SDK 5.0.1xx? (package and branch).

My current understanding that it is Microsoft.DotNet.Common.ProjectTemplates.5.0 only, and other versions are not used (based on clean test of SDK 5.0.xx  
I briefly checked sdk repo, and couldn't find the versions that are included. ItemTemplates are mentioned in https://github.com/dotnet/sdk/blob/master/eng/Version.Details.xml, but not ProjectTemplates.

**Comment by ViktorHofer** [comment]
@vlada-shubina would it make sense to continue this discussion in an issue so we can unblock this PR? I would like to get the updated templates into a 6.0 SDK.

**Comment by wli3** [comment]
@vlada-shubina I'll check that but note, it is ultimately template engine team to be responsible of the version flow.

**Comment by wli3** [comment]
@vlada-shubina  The "final" template versions are in dotnet/installer. The one in SDK is for testing. It is 5.0.0 in branch release/5.0.1xx https://github.com/dotnet/installer/blob/release/5.0.1xx/eng/Versions.props#L102
https://github.com/dotnet/installer/blob/release/5.0.1xx/eng/Versions.props#L34

**Review by vlada-shubina — APPROVED** [review]

**Comment by ViktorHofer** [comment]
@vlada-shubina looks like merging is blocked because it requires 2 approving reviews.

**Review by AR-May — APPROVED** [review]

**Pull request merged**
