### PR TITLE
Replaced string literals with resource strings

### LINKED ISSUE #3058: [Localizer] Replace string literals in logs with localizable resource strings
There are calls to `ILogger.Log(...)` where the log string is provided as literal. This should be fetched from a resource file to allow localizations.

- Move string literals to LocalizedStrings.resx file.

**tasks**
1. Create a resource file in _Microsoft.TemplateEngine.TemplateLocalizer.Core_
1. Create resource entries for each ILogger.Log* entry 
1. Update ILogger.Log* calls with the corresponding resource

**exit criteria**
1. All Logger.Log* calls adopted localization scheme.

### PR DESCRIPTION
**Pull request by bozturkMSFT**
### Problem
Closes #3058 

### Solution
String literals were replaced with resource strings.

### Checks:
- [ ] Added unit tests
- [ ] Added `#nullable enable` to all the modified files [?](https://github.com/dotnet/templating/wiki/Contributing#coding-style)

### CODE REVIEW

**Review by DavidKarlas — APPROVED** [review]
I'm not 100% if its worth translators time to localize debug message

**Review by vlada-shubina — APPROVED** [review]

**Comment by vlada-shubina** [comment]
I agree, we agreed with @KathleenDollard that debug messages might not be localized.

**Comment by bozturkMSFT** [comment]
I added the debug strings with the intention of template author using them to figure out why their strings was not included in the final output. So, it is not for us to investigate a bug, but it is for authors to investigate the problems with their template.json.

I can change this to a different log level, but one level above this is "Information" then it is "Warning", "Error" and "Critical". Which means too many things would be under "Information" (since I can't push current messages to "Warning" level).

**Comment by bozturkMSFT** [comment]
Let me know what you think and I will make a new PR if needed. I will merge this one to save time here.

**Pull request merged**
