### PR TITLE
Allow data columns in grids to shrink to fit the screen buffer width

### LINKED ISSUE #361: dotnet new -l : Table view can be improved on.
# Issue
The combined length of the **Template**(name), **Short Name**(shortName) & **Tags**(classifications) fields causes unpleasant line-breaks when greater than the width of your console.  Ultimately this equates to a bad UX.   

default

# Reproduce
When defining your template meta-data in **template.json**, add a large **name**, **shortName**, **classifications** or combination of the threes.

# Possible solutions
### 1

- Determine an average default console width.  For example, you can use the default width cmd or powershell opens with on windows. 
- Truncate a determined combination (add ellipsis) of the three fields in question, so that there will be no break.
- The user would be able to then drill down into that template for more details and a full view of any possible truncated strings. 

### 2

- Abandon the table view all to together in favor of a stacked view.
- To be quite honest, this seems to be best practice these days.
- If you have a lot of templates, finding one might be a bit hard but I don't believe that this issue is fixed with a table either.

### LINKED ISSUE #1815: dotnet new usage results in line wrapping under default console size
## Steps to reproduce
dotnet new

## Expected  behavior
text is concisely displayed and readable, no line wrapping

## Actual behavior
many spaces between each template type, header bar is line wrapping
image

It seems that the table is formatted in a way such that it measures the maximum string length then pads everything to be that wide.  EG: Max(lineLengths).  Instead you should probably consider the minimum(consoleWidth, max(lineLengths)) for the table width and individual cells in the table should be word-wrapped to a new line at appropriate offset.

## Environment data
`dotnet --info` output:
```
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-preview4-010757
 Commit:    df11eb9367

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100-preview4-010757\

Host (useful for support):
  Version: 3.0.0-preview4-27514-03
  Commit:  f77d28bb3f

.NET Core SDKs installed:
  2.1.600 [C:\Program Files\dotnet\sdk]
  3.0.100-preview4-010757 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview4-19163-08 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview4-27514-03 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0-preview4-27512-47 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

### LINKED ISSUE #2062: The table in "dotnet new" is too big
When I open a new terminal on Windows and run `dotnet new`, this is what I see:

Notice that:

1. Most of the visible templates are some of the least used ones (I think). Accessing the interesting information requires quite a lot of scrolling or resizing the terminal window.
2. Many of the visible lines are empty (or almost empty), because the table is too wide.

I think this is not good enough, especially considering that this might be one of the first things a newcomer to .Net Core will see.

What I think should be done:

1. Decrease the width of the table.

    Since the only row that's wider than the default terminal window width is Razor Class Library (see the image above), this could be as simple as removing "Razor Class Library" from its tags.

2. Decrease the height of the table.

    The table currently contains 30 entries and some of them are for fairly niche technologies (e.g. Dotnet local tool manifest file) or contain lots of variations, some of which probably aren't commonly used (ASP.NET Core).

    Maybe the less commonly used items should be hidden when running `dotnet new` and only shown for `dotnet new --list`? Though I'm not sure how to decide how many items to show and which items to show by default (telemetry could help, but recent data is not available, at least not publicly: https://github.com/dotnet/core/issues/2213).

What do you think?

### PR DESCRIPTION
**Pull request by Eilon**
Updated layout logic for grid to allow a single column to be maked as `shrinkIfNeeded`. If the screen buffer is not wide enough to fit the data, the shrinkable column will be shrunk to fit the screen exactly. If the screen is so small so that there isn't even room for that, the rendering uses a minimum width, so it looks a bit ugly, but not as bad as it might otherwise look with huge wrapped text.

The only help grid that is marked as having a shrinkable column is the one that lists the installed templates.

Fixes these issues:
* dotnet new -l : Table view can be improved on. #361
* dotnet new usage results in line wrapping under default console size #1815
* The table in "dotnet new" is too big #2062

Note: This PR contains a few commits because of some code cleanup that doesn't change any functionality. The main part is the last commit that changes the grid layout functionality.

Here are examples of the new rendering:

Full width:

```
Templates                                    Short Name                Language          Tags
---------------------------------------      --------------------      ------------      --------------------
Experimental Mobile Blazor Bindings App      mobileblazorbindings      [C#]              Blazor/Xamarin.Forms
NUnit 3 Test Project                         nunit                     [C#], F#, VB      Test/NUnit
NUnit 3 Test Item                            nunit-test                [C#], F#, VB      Test/NUnit
```

A bit narrower (first item shortened):

```
Templates                                  Short Name                Language          Tags
-------------------------------------      --------------------      ------------      --------------------
Experimental Mobile Blazor Binding...      mobileblazorbindings      [C#]              Blazor/Xamarin.Forms
NUnit 3 Test Project                       nunit                     [C#], F#, VB      Test/NUnit
NUnit 3 Test Item                          nunit-test                [C#], F#, VB      Test/NUnit
```

Even narrower (all items shortened):

```
Templates             Short Name                Language          Tags
----------------      --------------------      ------------      --------------------
Experimental ...      mobileblazorbindings      [C#]              Blazor/Xamarin.Forms
NUnit 3 Test ...      nunit                     [C#], F#, VB      Test/NUnit
NUnit 3 Test ...      nunit-test                [C#], F#, VB      Test/NUnit
```

So narrow that even column header is shortened:

```
Temp...      Short Name                Language          Tags
-------      --------------------      ------------      --------------------
Expe...      mobileblazorbindings      [C#]              Blazor/Xamarin.Forms
NUni...      nunit                     [C#], F#, VB      Test/NUnit
NUni...      nunit-test                [C#], F#, VB      Test/NUnit
```

And when it's extremely narrow that even the non-shrinkable column can't fit, it renders it at its minimum allowed width, which is 5. It looks silly, but it always did, and there's not much you can do when the screen is absurdly narrow:

```
Te...      Short Name                Language          Tags

-----      --------------------      ------------      --------------
------
Ex...      mobileblazorbindings      [C#]              Blazor/Xamarin
.Forms
NU...      nunit                     [C#], F#, VB      Test/NUnit

NU...      nunit-test                [C#], F#, VB      Test/NUnit
```

Fixes #361
Fixes #1815
Fixes #2062

### CODE REVIEW

**Comment by Eilon** [comment]
For comparison, without this change, the table would render like this:

```
Templates                                    Short Name                Language
       Tags
----------------------------------------------------------------------------------
---------------------------
Experimental Mobile Blazor Bindings App      mobileblazorbindings      [C#]
       Blazor/Xamarin.Forms
NUnit 3 Test Project                         nunit                     [C#], F#, V
B      Test/NUnit
NUnit 3 Test Item                            nunit-test                [C#], F#, V
B      Test/NUnit
```

And as seen in all the linked issues, many people found this behavior to be undesirable.

**Comment by Eilon** [comment]
For some reason one test fails when I run from my command line, and fails on CI, but doesn't repro in VS. I don't believe this PR changes anything to do with this test. Everything passes in `master` and in my [other PR](#2268).

This is the location of the failure:

```
 NupkgReinstallDoesntRemoveTemplates
Assert.Equal() Failure\r\nExpected: 0\r\nActual:   1
   at Microsoft.TemplateEngine.Cli.UnitTests.TemplateInstallTests.NupkgInstallTests.NupkgReinstallDoesntRemoveTemplates() in
...\test\Microsoft.TemplateEngine.Cli.UnitTests\TemplateInstallTests\NupkgInstallTests.cs:line 38
```

My change doesn't affect how/whether/if anything gets installed or uninstalled. It only changes how tables are rendered.

I will continue to investigate.

**Comment by RehanSaeed** [comment]
This is great stiff. Now if we could also fix the output from `dotnet new console --help` which produces very ugly output, I'd be very happy:

https://github.com/dotnet/templating/issues/1544

**Comment by Eilon** [comment]
@vijayrkn any idea about this failing test? I will try to debug it more but because it doesn't reproduce in VS it's hard to debug 😦

**Comment by Eilon** [comment]
@RehanSaeed I might take a stab at that one too!

**Comment by vijayrkn** [comment]
> @vijayrkn any idea about this failing test? I will try to debug it more but because it doesn't reproduce in VS it's hard to debug 😦

I haven't worked on this repo much except for upgrading to the newer build system and branding updates. @phenning - can you please take a look?

**Comment by RehanSaeed** [comment]
@Eilon Cool! If you need a real project with dozens of options to test against, try [.NET Boxed](https://github.com/Dotnet-Boxed/Templates):

```bash
dotnet new --install Boxed.Templates
```

**Comment by vijayrkn** [comment]
Running all the tests does cause the issue to repro in VS. Running the test by itself doesn't fail. May be some other test is altering the environment. I will try to debug more & see if I can find which test is causing this issue. 

image

**Comment by Eilon** [comment]
Oh funny I didn't try running all tests, I only ever ran the single test! That should be a lot easier to debug. I'll give it a try as well but probably not for several days (family in town!).

**Comment by Eilon** [comment]
Indeed, I can get the test to fail in VS if I run all tests. But if I _debug_ all tests then it doesn't fail. Very difficult to debug this one.

**Comment by Eilon** [comment]
After doing the cheesiest of "printf() debugging" I think I found the problem. It boils down to a swallowed exception:

```
System.IO.IOException: The handle is invalid
   at System.ConsolePal.GetBufferInfo(Boolean throwOnNoConsole, Boolean& succeeded)
   at System.Console.get_BufferWidth()
   at Microsoft.TemplateEngine.Utils.EngineEnvironmentSettings.DefaultEnvironment.get_ConsoleBufferWidth() in C:\GitHub\eilon-dotnet-templating\src\Microsoft.TemplateEngine.Utils\EngineEnvironmentSettings.cs:line 105
   at Microsoft.TemplateEngine.Cli.HelpFormatter`1.Layout() in C:\GitHub\eilon-dotnet-templating\src\Microsoft.TemplateEngine.Cli\HelpFormatter.cs:line 117
   at Microsoft.TemplateEngine.Cli.HelpAndUsage.HelpForTemplateResolution.DisplayTemplateList(IReadOnlyList`1 templates, IEngineEnvironmentSettings environmentSettings, String language, String defaultLanguage) in C:\GitHub\eilon-dotnet-templating\src\Microsoft.TemplateEngine.Cli\HelpAndUsage\HelpForTemplateResolution.cs:line 204
   at Microsoft.TemplateEngine.Cli.HelpAndUsage.HelpForTemplateResolution.DisplayHelpForAmbiguousTemplateGroup(TemplateListResolutionResult templateResolutionResult, IEngineEnvironmentSettings environmentSettings, INewCommandInput commandInput, IHostSpecificDataLoader hostDataLoader, ITelemetryLogger telemetryLogger, String defaultLanguage) in C:\GitHub\eilon-dotnet-templating\src\Microsoft.TemplateEngine.Cli\HelpAndUsage\HelpForTemplateResolution.cs:line 134
   at Microsoft.TemplateEngine.Cli.HelpAndUsage.HelpForTemplateResolution.CoordinateHelpAndUsageDisplay(TemplateListResolutionResult templateResolutionResult, IEngineEnvironmentSettings environmentSettings, INewCommandInput commandInput, IHostSpecificDataLoader hostDataLoader, ITelemetryLogger telemetryLogger, TemplateCreator templateCreator, String defaultLanguage) in C:\GitHub\eilon-dotnet-templating\src\Microsoft.TemplateEngine.Cli\HelpAndUsage\HelpForTemplateResolution.cs:line 34
   at Microsoft.TemplateEngine.Cli.New3Command.EnterMaintenanceFlow() in C:\GitHub\eilon-dotnet-templating\src\Microsoft.TemplateEngine.Cli\New3Command.cs:line 296
```

And this is caused when output is redirected so the screen-width calculator can't get the screen width because _there is no screen_. I suspected this was a problem and thought I defended against it, but apparently not. I will update this PR.

**Comment by Eilon** [comment]
Though, I still don't understand why this would fail only when running all tests, without debugger. That makes no sense to me at all. As far as I know the same "product code" is always running. Maybe there's something about running multiple tests that causes the output redirection to happen differently, so the product code is running in a slightly different environment, so it fails? Either way, I think it's fair to say there's a bug in my PR, so I'll update the code anyway.

**Comment by Eilon** [comment]
Boom, all green!

**Comment by Eilon** [comment]
Thank you @vijayrkn !!!

**Pull request merged**
