### PR TITLE
[release/3.1] Mark template packages as nonshipping

### PR DESCRIPTION
**Pull request by wtgodbe**
These are evidently transport packages, not shipping packages intended for nuget.org. Marking them as such

### CODE REVIEW

**Comment by wtgodbe** [comment]
ping @phenning @grinrag @vijayrkn - does this change look good to you?

**Comment by phenning** [comment]
Well, we do want to publish these to NuGet.org don't we? The dotnet new command lets you install updated templates direcly from nuget by specifying a version string on the install command. We probably don't want to update the 3.1 template packs from any branch other then the release 3.1 branch though.

I'm not sure if these are getting uploaded now, or what the mechanism is for that exactly.

**Comment by mmitche** [comment]
It does not appear that the templates publish regularly to nuget.org today. Should this be the case?

**Comment by wtgodbe** [comment]
@phenning these don't regularly get published to nuget. If they should, we should figure out why they aren't being published despite being marked as shipping. Otherwise, it's correct to mark them nonshipping, for consistency & compliance with our release-day infra

**Comment by vijayrkn** [comment]
These should be shipped to NuGet. @grinrag - Can you please do the needful?

**Comment by grinrag** [comment]
@wtgodbe I see that the last update was made 5 months ago - https://www.nuget.org/packages/Microsoft.DotNet.Common.ProjectTemplates.3.1/
Not sure, if there were any changes in the template since then.

I need to ask PM about our plans to have this been automated (if not yet).

@ChrisSfanos, as I know, previously you helped us to publish this package to nuget.org. Could you, please, explain the process?

**Comment by wtgodbe** [comment]
I would have assumed that the release day infrastructure would automate the publishing of these packages, by virtue of them being present in the 'shipping' folder of the network share - @leecow @jamshedd is that not the case?

**Comment by ChrisSfanos** [comment]
I just log into NuGet.org and do the publish - so if you hand off the package(s) that you need published, I can do that

**Comment by leecow** [comment]
For 3.1+, the `gatherdrop` process stages nuget packages to be published to a publish_files\nuget folder for the drop on CORE_BUILDS. It seems like this part of the tooling does not know about the packages.

**Comment by wtgodbe** [comment]
> It seems like this part of the tooling does not know about the packages.

@leecow @jamshedd @rbhanda how can we get them added? It seems the easiest way to solve this problem would be to include them in the existing automation

**Comment by wtgodbe** [comment]
ping @leecow @jamshedd @rbhanda for the question above

**Comment by mmitche** [comment]
> ping @leecow @jamshedd @rbhanda for the question above

It's a change in darc: https://github.com/dotnet/arcade/issues/6048

**Pull request closed without merging**
