### PR TITLE
Temporarily remove VB templates

### PR DESCRIPTION
**Pull request by mlorbetske**
@livarcocc @srivatsn 

Filed https://github.com/dotnet/templating/issues/730 to track re-adding when the support is there

### CODE REVIEW

**Comment by srivatsn** [comment]
Will this remove them from VS as well?

**Comment by mlorbetske** [comment]
VS would no longer install them, but the VSTemplate file would also need to be removed

**Comment by srivatsn** [comment]
No we need this in VS. VS fully supports building VB projects. The CLI doesn't have the VB compiler yet. So we need to only selectively remove these templates from the CLI - not from VS.

**Comment by mlorbetske** [comment]
OK, closing this PR & associated bug. We need to add an engine feature to allow hiding these. @seancpeters is starting on that now.

**Comment by mlorbetske** [comment]
Bug for the new feature is #734

**Pull request closed without merging**
