### PR TITLE
Add --interactive flag

### PR DESCRIPTION
**Pull request by kroymann**
Add --interactive flag which if specified is passed through to the internal dotnet restore calls. This addresses issue #1747

### CODE REVIEW

**Comment by thecontrarycat** [comment]
It would be nice to see this PR merged.  As an Azure Artifacts user it's a real pain to try to get the `dotnet new` commands to work as it is too stupid to ignore sources that 401.

**Comment by michasHL** [comment]
@vijayrkn would you mind taking a lot at this PR.
We're really waiting for this feature to get into master to finally be able to use template nuget packages from our private feed.

**Comment by grinrag** [comment]
@KathleenDollard I would like to get your opinion on the UX for this new `--interactive` flag. Is is consistent across all the dotnet CLI tools? Does it do what user could expect from that parameter? 

The changes itself LGTM, and we can merge after you ack.

**Comment by grinrag** [comment]
This PR is a part of the fix for the issue #179.

**Pull request merged**
