### PR TITLE
[release/6.0.4xx] rtm branding

### PR DESCRIPTION
**Pull request by vlada-shubina**
RTM branding for 6.0.4xx

### CODE REVIEW

**Review by JanKrivanek — APPROVED** [review]

**Comment by vlada-shubina** [comment]
@marcpopMSFT @dotnet/dotnet-cli please confirm version of `System.CommandLine` and NuGet libs.

**Comment by marcpopMSFT** [comment]
@vlada-shubina , looks like there's one more change from nuget coming moving us to 128. I think the sdk can take it without templating (Chet confirmed no breaking changes so the two versions should be compatible).
[[release/6.0.4xx] Update dependencies from nuget/nuget.client by dotnet-maestro[bot] · Pull Request #26561 · dotnet/sdk (github.com)](https://github.com/dotnet/sdk/pull/26561)

**Comment by vlada-shubina** [comment]
> @vlada-shubina , looks like there's one more change from nuget coming moving us to 128. I think the sdk can take it without templating (Chet confirmed no breaking changes so the two versions should be compatible). [[release/6.0.4xx] Update dependencies from nuget/nuget.client by dotnet-maestro[bot] · Pull Request #26561 · dotnet/sdk (github.com)](https://github.com/dotnet/sdk/pull/26561)

do you know if NuGet version will be updated to stable before the release (e.g. 6.3.0)? or will be released with prerelease package?

**Comment by marcpopMSFT** [comment]
My understanding is that Nuget has a separate build process for these internal codeflow packages and they never have stable branding. For example, 6.0.1xx is currently shipping with "6.0.2-rc.5".  I believe the 128 build is the last known change for 17.3/6.0.300.

**Pull request merged**
