### PR TITLE
Update .NET 5 templates with net5.0 tfm

### PR DESCRIPTION
**Pull request by ViktorHofer**
Contributes towards https://github.com/dotnet/sdk/issues/10756

cc @grinrag and Jose Aguilar (what's your GH handle? ;))

### CODE REVIEW

**Comment by grinrag** [comment]
thank you for the contributions @ViktorHofer ! I will test the changes.
cc @donJoseLuis

**Comment by ViktorHofer** [comment]
@grinrag can we merge this? this will require a new SDK anyway to make restore and the sdk parsing logic work.

**Comment by vijayrkn** [comment]
@phenning - How would this change impact the templates displayed in VS?

**Comment by phenning** [comment]
Pretty severely. we really needed time to proof VS for this change.

**Comment by vijayrkn** [comment]
@ViktorHofer - This will break a lot of our VS tooling scenarios. Can we make this change only in preview3 branch and not in preview2 branch so that there is time for tooling to react to this change.

**Comment by ViktorHofer** [comment]
How is the 5.0-preview2 branch connected to VS? That branch versions with dotnet. If you need to ship these templates to VS as well the I recommend creating a 16.x branch and not include my template change. That said I know that nuget ships the net5.0 compatibility feature to VS for  16.6.

**Comment by phenning** [comment]
We are talking about release timing, not a hard dependency here.

**Comment by ViktorHofer** [comment]
I see, thanks for clarifying.

> Can we make this change only in preview3 branch and not in preview2 branch so that there is time for tooling to react to this change.

Unfortunately not, as for 5.0-preview2 the goal is to land the net5.0 TFM change. Here's the tracking issue: https://github.com/dotnet/sdk/issues/10756.

> Pretty severely. we really needed time to proof VS for this change.

cc @leecow @SteveCarrollMSFT

**Pull request merged**
