### PR TITLE
Coalesce respects empty string as user input

### PR DESCRIPTION
**Pull request by GangWang01**
### Problem
Coalesce doesn't respect empty string as user input.

### Solution
Currently coalesce macro handles empty value for string is equivalent to null. So differentiate empty string from null.

### Checks:
- [x] Added unit tests
- [ ] Added `#nullable enable` to all the modified files [?](https://github.com/dotnet/templating/wiki/Contributing#coding-style)

### CODE REVIEW

**Review by JanKrivanek — APPROVED** [review]
Thank you!

**Review by vlada-shubina — APPROVED** [review]

**Comment by YuliiaKovalova** [comment]
@vlada-shubina , do we plan to backport this fix to 7.0.4xx?

**Comment by vlada-shubina** [comment]
> @vlada-shubina , do we plan to backport this fix to 7.0.4xx?

it would be good, if the backport is easy (should be).

**Comment by YuliiaKovalova** [comment]
@GangWang01 , could you backport it to release/7.0.4xx?

**Pull request closed without merging**
