### PR TITLE
Update NuGet.Configuration, NuGet.Credentials and NuGet.Protocol

### PR DESCRIPTION
**Pull request by v-wuzhai**
Fixes #6952   #6949  #6951

### CODE REVIEW

**Comment by v-wuzhai** [comment]
@dotnet/templating-engine-maintainers would you be able to review these changes?

**Review by MiYanni — APPROVED** [review]

**Comment by v-wuzhai** [comment]
@mthalman @dotnet/templating-engine-maintainers Could you take a look at the SB errors here?

**Comment by mthalman** [comment]
The packages listed in the error will need to be added to the [SBRP repo](https://github.com/dotnet/source-build-reference-packages). Instructions for that are here: https://github.com/dotnet/source-build-reference-packages#adding-new-packages. Once merged in that repo, it will cause a dependency flow to update the referenced SBRP in this repo. Merge that update in this PR and the error should go away.

**Comment by v-wuzhai** [comment]
@dotnet/templating-engine-maintainers @mthalman I'm not sure if we don't need updates for these packages?

**Comment by mthalman** [comment]
It would seem this PR was accidentally closed, right? In your post for https://github.com/dotnet/source-build-reference-packages/pull/783, it said "fix xxxx" which caused this PR to be closed when that one was merged.

**Pull request merged**
