### PR TITLE
[release/7.0.2xx] Fix the order processing ComputedMacros and GeneratedSymbolMacros in Derived

### LINKED ISSUE #6291: Derived symbol value is empty when it is in Symbol geneator
in dotnet 7.0.2, When we reference a derived symbol in a symbol generator, the generated symbol value does not contain the derived symbol.
run 
`dotnet new *** --ClientName test`

The value of  `PackageName` : 
Actual: `Package.`
expected:  `Package.Test`

It works fine in dotnet 3.1.

```
"symbols": {
"clientName": {
      "type": "parameter",
      "datatype": "text",
      "isRequired": true,
      "description": "client name"
    },
"ClientNameCapitalCase": {
      "type": "derived",
      "datatype": "text",
      "valueSource": "clientName",
      "valueTransform": "firstUpperCase",
      "replaces": "Template"
    },
"PackageName": {
      "type": "generated",
      "generator": "join",
      "parameters": {
        "symbols": [
          {
            "type": "const",
            "value": "Package"
          },
          {
            "type": "ref",
            "value": "ClientNameCapitalCase"
          }
        ],
        "separator": "."
      },
    },
}
```

### PR DESCRIPTION
**Pull request by GangWang01**
Fixes #6291
## Description
Before the bug occurrence, the right sequence of symbols usage was:
derived -> generated -> computed
After introducing the issue, it became possible to use computed or generated in derived (**INVALID** scenario).
During the analysis, we checked if any templates were created with invalid configurations between release/7.0.2xx - release/7.0.4xx versions.
I used packages from nuget.org. 
2333 packages are considered -> 57 templates use derived symbols -> 0 templates have invalid configuration.

Regression is caused by https://github.com/dotnet/templating/pull/5591. 

## Customer Impact

The value of  `PackageName` : 
**Actual**: `Package.`
**Expected**:  `Package.Test`

```
"symbols": {
"clientName": {
      "type": "parameter",
      "datatype": "text",
      "isRequired": true,
      "description": "client name"
    },
"ClientNameCapitalCase": {
      "type": "derived",
      "datatype": "text",
      "valueSource": "clientName",
      "valueTransform": "firstUpperCase",
      "replaces": "Template"
    },
"PackageName": {
      "type": "generated",
      "generator": "join",
      "parameters": {
        "symbols": [
          {
            "type": "const",
            "value": "Package"
          },
          {
            "type": "ref",
            "value": "ClientNameCapitalCase"
          }
        ],
        "separator": "."
      },
    },
}
```

## Solution

Fallback to the scenario where it isn't possible to use computed/generated symbols in derived.

## Regression

Yes. Introduced in release/7.0.2xx.

## Testing
Covered with integration/unit tests for checking possible regression scenarios.

## Risk
Low. The risk analysis was conducted for preventing breaking users that could start using invalid scenarios.

### CODE REVIEW

**Review by YuliiaKovalova — APPROVED** [review]
Looks good to me!

**Comment by GangWang01** [comment]
@YuliiaKovalova The tests need to be ported to main, release/7.0.3xx, release/7.0.4xx and release/8.0.1xx-preview3. How do you think?

**Comment by YuliiaKovalova** [comment]
> @YuliiaKovalova The tests need to be ported to main, release/7.0.3xx, release/7.0.4xx and release/8.0.1xx-preview3. How do you think?

yes, let's do that.

**Comment by GangWang01** [comment]
> > @YuliiaKovalova The tests need to be ported to main, release/7.0.3xx, release/7.0.4xx and release/8.0.1xx-preview3. How do you think?
> 
> yes, let's do that.

For release/7.0.3xx and release/7.0.4xx, they also need the fix. I'd like to ensure with the change the tests in sdk pass and then port the change to these two branches.

**Comment by YuliiaKovalova** [comment]
> > > @YuliiaKovalova The tests need to be ported to main, release/7.0.3xx, release/7.0.4xx and release/8.0.1xx-preview3. How do you think?
> > 
> > 
> > yes, let's do that.
> 
> For release/7.0.3xx and release/7.0.4xx, they also need the fix. I'd like to ensure with the change the tests in sdk pass and then port the change to these two branches.

Sounds reasonable to me!

**Comment by vlada-shubina** [comment]
This PR needs approval for servicing in 7.0.2xx and 7.0.3xx, @YuliiaKovalova could you please handle this and update the description of the ticket?

Thanks

**Comment by GangWang01** [comment]
@YuliiaKovalova I missed the tests for the case that computed symbol depends on generated symbol. I'm adding the tests now. Please wait a while and see if the new test can pass before merging.

**Comment by GangWang01** [comment]
For the other case that computed symbol and derived symbol depends on generated symbol, the change swapping the order processing ComputedMacros and GeneratedSymbolMacros failed the newly added tests. Computed symbol was evaluated correctly but derived symbol behaved to be evaluated as empty string in ` fileRename `, ` replaces `.
Without the change the case could pass, but the issue this PR fixed appeared…

Though the issue this PR fixed  doesn’t happen to .NET 6 and .NET 7.0.105, for the other case that computed symbol and derived symbol depends on generated symbol they don’t work well. I checked with dotnet 6.0.408 and dotnet 7.0.105. They have a little different behavior.

- dotnet 6.0.408 : computed symbol was evaluated correctly; derived symbol behaved to be evaluated as empty string in ` fileRename `, ` replaces `.
- dotnet 7.0.105 : computed symbol was evaluated correctly; derived symbol behaved to have no effect to the target of ` fileRename `, ` replaces `.

I also checked with main branch locally using the newly added tests. The tests failed too.

We need a good solution to evaluate derived symbol in the two cases.

**Comment by GangWang01** [comment]
> 



> For the other case that computed symbol and derived symbol depends on generated symbol, the change swapping the order processing ComputedMacros and GeneratedSymbolMacros failed the newly added tests. Computed symbol was evaluated correctly but derived symbol behaved to be evaluated as empty string in `fileRename`, `replaces`. Without the change the case could pass, but the issue this PR fixed appeared…
> 
> Though the issue this PR fixed doesn’t happen to .NET 6 and .NET 7.0.105, for the other case that computed symbol and derived symbol depends on generated symbol they don’t work well. I checked with dotnet 6.0.408 and dotnet 7.0.105. They have a little different behavior.
> 
> * dotnet 6.0.408 : computed symbol was evaluated correctly; derived symbol behaved to be evaluated as empty string in `fileRename`, `replaces`.
> * dotnet 7.0.105 : computed symbol was evaluated correctly; derived symbol behaved to have no effect to the target of `fileRename`, `replaces`.
> 
> I also checked with main branch locally using the newly added tests. The tests failed too.
> 
> It looks like the problem exists in evaluating derived symbol while processing macros. We need a good solution to evaluate derived symbol in the two cases.
> 
> * generated symbol refers to derived symbol
> * the value source of derived symbol is from generated symbol

As Vlada told offline, we decided to fix the case "derived symbol is used in generated symbol". It's obvious that "generated symbol is used in derived symbol" stops working. The case that generated symbol is used in derived symbol is invalid.

We can either calculate all derived symbols first to make them available for generated, or vice versa. To support both, we need to analyze dependencies between symbols, and this is part of separate issue which we are not doing yet.

**Review by YuliiaKovalova — APPROVED** [review]

**Pull request merged**
