### PR TITLE
Fix PostActionProcessorBase.GetConfiguredFiles to be able to use simple project names

### PR DESCRIPTION
**Pull request by knollsen**
### Problem
The `PostActionProcessorBase` contains the method `GetConfiguredFiles`. It is used in the post actions `AddProjectsToSolution`, `DotnetRestore` and `AddReference` to retrieve project files specified in `args`.

The method is supposed to accept both a string with project names and lists of project names, however I noticed that only a list will result in a working post action. This is because the argument is given to `NewtonSoft`'s `JToken.Parse`, but only after it was already parsed from JSON once. Because of that, a value in the JSON like `"targetFiles": "MyApp.csproj"` will be given to `JToken.Parse` without quotation marks simply as `MyApp.csproj`, which is not valid JSON, resulting in an exception. For arrays, this method works as expected.

### Solution
My simple fix would be to add quotation marks around the argument in case the argument is not a list or it does not already have quotation marks. This is not very elegant, an alternative would be not to use `JToken.Parse` anymore in the method, I am open to any suggestions regarding this.

I added unit tests for all the post action processors that are using the method, for each processor one for the case that already worked before with the list and one for the case that works after the fix with the project name as the argument.

### Checks:
- [x] Added unit tests
- [x] Added `#nullable enable` to all the modified files [?](https://github.com/dotnet/templating/wiki/Contributing#coding-style)

### CODE REVIEW

**Review by JanKrivanek — APPROVED** [review]
Thank you for the contribution!
Simple and well tested - looks good to me!

**Comment by vlada-shubina** [comment]
I would prefer to get it fixed when post action model is created:
https://github.com/dotnet/templating/blob/a4a90c52d16f2de5e545c00c59ad2ccd8b4710a6/src/Microsoft.TemplateEngine.Orchestrator.RunnableProjects/PostActionModel.cs#L128
to
```
args.Add(argInfo.Name, argInfo.Value.ToString(Newtonsoft.Json.Formatting.None))
```

When Formatting.None or Formatting.Indented is used, `ToString` will generate quotes.
See https://github.com/JamesNK/Newtonsoft.Json/issues/2144.

**Comment by knollsen** [comment]
> I would prefer to get it fixed when post action model is created:
> 
> https://github.com/dotnet/templating/blob/a4a90c52d16f2de5e545c00c59ad2ccd8b4710a6/src/Microsoft.TemplateEngine.Orchestrator.RunnableProjects/PostActionModel.cs#L128
> 
> 
> to
> ```
> args.Add(argInfo.Name, argInfo.Value.ToString(Newtonsoft.Json.Formatting.None))
> ```
> 
> When Formatting.None or Formatting.Indented is used, `ToString` will generate quotes. See [JamesNK/Newtonsoft.Json#2144](https://github.com/JamesNK/Newtonsoft.Json/issues/2144).

Thank you! I tried out the ToString(Newtonsoft.Json.Formatting.None), it works like you said, it returns the `JProperty`.'s value with quotation marks around it. 

However, using it here in `PostActionModel` will result in all string arguments having quotation marks around them, which breaks many things as only _some_ arguments are put through `JToken.Parse` and some are used directly as strings. 

For example, in the `AddReferencePostActionProcessor`, there's a check on the type of reference using string comparison, which doesn't work anymore, as `"\"project\"" != "project"`.

**Comment by vlada-shubina** [comment]
I see, in this case it doesn't seem to be an option.
I see no point in adding the quotes just to get through parsing. 
we may change the logic as:
```
if (JToken.TryParse(arg, out JToken jtoken))
{
    if (jtoken is string)
    {
          //treat as JSON string
    }
    else if (jtoken is Jarray)
    {
           //treat as JSON array
    }
   //not expected
}
else
{
    //treat as non JSON string
}

```

iirc `TryParse` is not available, we can create a simple one with try-catch.

**Comment by knollsen** [comment]
> I see, in this case it doesn't seem to be an option. I see no point in adding the quotes just to get through parsing. we may change the logic as:
> 
> ```
> if (JToken.TryParse(arg, out JToken jtoken))
> {
>     if (jtoken is string)
>     {
>           //treat as JSON string
>     }
>     else if (jtoken is Jarray)
>     {
>            //treat as JSON array
>     }
>    //not expected
> }
> else
> {
>     //treat as non JSON string
> }
> ```
> 
> iirc `TryParse` is not available, we can create a simple one with try-catch.

That's a great approach! I implemented the  `JToken.TryParse` method in `JTokenExtensions` as an extension method to `JToken` directly would need an instance of the class. Let me know if there's anything else I should change!

**Comment by vlada-shubina** [comment]
> > I see, in this case it doesn't seem to be an option. I see no point in adding the quotes just to get through parsing. we may change the logic as:
> > ```
> > if (JToken.TryParse(arg, out JToken jtoken))
> > {
> >     if (jtoken is string)
> >     {
> >           //treat as JSON string
> >     }
> >     else if (jtoken is Jarray)
> >     {
> >            //treat as JSON array
> >     }
> >    //not expected
> > }
> > else
> > {
> >     //treat as non JSON string
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > iirc `TryParse` is not available, we can create a simple one with try-catch.
> 
> That's a great approach! I implemented the `JToken.TryParse` method in `JTokenExtensions` as an extension method to `JToken` directly would need an instance of the class. Let me know if there's anything else I should change!

Looks good, thank you for implementing.

**Review by vlada-shubina — APPROVED** [review]

**Pull request merged**
