### PR TITLE
Remove EOL openSuSE 42.1

### PR DESCRIPTION
**Pull request by mmitche**

### CODE REVIEW

**Comment by mmitche** [comment]
@dotnet-bot test ci please

**Comment by mmitche** [comment]
@mlorbetske Can you approve this?

**Comment by mlorbetske** [comment]
Could you elaborate on what this is for please? The branch being targeted shouldn't be building regularly anymore

@seancpeters

**Comment by mmitche** [comment]
@mlorbetske 42.1 is part of CI for this branch.  42.1 has reached end of life and the OS image we are using cannot be updated or modified at this point (package feeds are gone).  This is to remove this CI leg so that the image can be cleaned up.

**Comment by mlorbetske** [comment]
I approve, but am out of office, please with with Sean to get these through

**Comment by seancpeters** [comment]
I can merge all these if they're good to go.

**Comment by mmitche** [comment]
They are, thanks! :)

**Comment by seancpeters** [comment]
@mlorbetske - strange, I'm apparently not authorized to merge into this branch.

**Comment by mmitche** [comment]
@seancpeters Luckily I can :)

**Comment by seancpeters** [comment]
How Bizarre, how bizarre.

**Pull request merged**
