### PR TITLE
[release/8.0.1xx] Update dependencies from dotnet/arcade

### PR DESCRIPTION
**Pull request by v-wuzhai**

### CODE REVIEW

**Review by marcpopMSFT — APPROVED** [review]

**Comment by marcpopMSFT** [comment]
@MiYanni I believe you were looking at some of the analysis warnings. Looks like Jason updated a bunch of tests for that.

**Review by MiYanni — APPROVED** [review]

**Comment by MiYanni** [comment]
PERFECT! I was trying to fix these and the `.ConfigureAwait(false)` ones were broken in the auto-fix resolver in VS. Thank you!!!

**Comment by ViktorHofer** [comment]
This PR consumed the Arcade from the main branch instead of release/8.0: https://github.com/dotnet/arcade/commit/0e89c8d7ddbb54510d9d0a757fda5126021b79f0. That's why you got these new analyzers showing up here.

We can keep the test updates but we should trigger a new Arcade subscription update and make sure that the subscription points to the right channel.

**Comment by ViktorHofer** [comment]
```
https://github.com/dotnet/arcade (.NET Eng - Latest) ==> 'https://github.com/dotnet/templating' ('release/8.0.1xx')
  - Id: 0d66de4b-fd8f-44dd-a789-08db9e4038dc
  - Update Frequency: EveryDay
  - Enabled: True
  - Batchable: False
  - PR Failure Notification tags:
  - Merge Policies:
    Standard
  - Last Build: 20231018.2 (6a5ca678aef84f34a1fccc46f76623f41da56553)
```

This is wrong. dotnet/templating's release/8.0.1xx branch must not consume Arcade's main branch as that already targets .NET 9. @marcpopMSFT @mmitche any idea who owns this stuff for templating? We need to make sure that they understand the issue here.

**Comment by MiYanni** [comment]
@ViktorHofer So, @joeloff and myself own Templating now, but clearly, it doesn't have the same configuration that we have for the SDK/Installer repos. I've done some adjustments yesterday, but I wasn't aware of this situation. I'm fairly new to DARC/codeflow, so I might need to work with @joeloff and do a review of the current configuration to see if it makes sense. Thank you for fix this!

**Comment by ViktorHofer** [comment]
No worries at all. Feel free to ping me in case you ever need help with codeflow :)

**Pull request merged**
