### PR TITLE
Versions.props cleanup

### PR DESCRIPTION
**Pull request by jcagme**
Remove `RestoreSources` from Versions.props in order to complete [step 2](https://github.com/dotnet/arcade/blob/master/Documentation/RestoreSourcesUpdateStatus.md#part-2)

@phenning can you PTAL?

### CODE REVIEW

**Comment by jcagme** [comment]
Ping...

**Comment by jcagme** [comment]
@phenning I've edited the description and added you, could you PTAL?

**Comment by phenning** [comment]
Do we also need these changes pushed for preview 8 or preview 9?

**Comment by jcagme** [comment]
If the Arcade version is >= 1.0.0-beta.19366.4 then I'd recommend you to do it as well.

Also, could you please merge the PR, I can't

**Pull request merged**
