### PR TITLE
Insert Testplatform 15.6.0-preview-20180109-01

### PR DESCRIPTION
**Pull request by smadala**
Release notes [here](https://github.com/smadala/vstest-docs/blob/c889dde09c59a9c58740796a4c3dc77d5262a0c1/docs/releases.md#1560-preview-20180109-01).
VS insertion PR [here](https://devdiv.visualstudio.com/DevDiv/VS.in%20Agile%20Testing%20IDE/_git/VS/pullrequest/100680?_a=overview) for VS 15.6 preview 3.

@mlorbetske rel/2.1.0-preview2 is right branch to get these templates to VS 15.6?

### CODE REVIEW

**Comment by mlorbetske** [comment]
We can produce the template packages for insertion into 15.6 from changes made to this branch, yes. We’ll let you know the package version to use when it’s available.

**Comment by mlorbetske** [comment]
We’ll need to cherry pick this change to master and release/2.1

**Comment by smadala** [comment]
Thanks @mlorbetske. These changes flow to master and release/2.1 without another PR?

**Comment by mlorbetske** [comment]
@smadala we've got it from here, no need for an additional PR

**Comment by mlorbetske** [comment]
@smadala 1.0.1-beta3-20180111-1281490 should contain your changes.

**Comment by smadala** [comment]
@mlorbetske Thanks for info.

**Pull request merged**
