### PR TITLE
Updated version of Microsoft.NET.Test.Sdk to 15.5.0-preview-20170914-09

### PR DESCRIPTION
**Pull request by harshjain2**
Updated version of Microsoft.NET.Test.Sdk to 15.5.0-preview-20170914-09

### CODE REVIEW

**Comment by harshjain2** [comment]
@dotnet-bot test this please.

**Comment by mlorbetske** [comment]
@dotnet-bot test CentOS7.1 x64 Debug Build please
@dotnet-bot test Debian8.2 x64 Debug Build please
@dotnet-bot test Linux x64 Release Build please
@dotnet-bot test Ubuntu x64 Release Build please
@dotnet-bot test Ubuntu16.04 x64 Debug Build please
@dotnet-bot test Ubuntu16.10 x64 Debug Build please

**Comment by harshjain2** [comment]
@dotnet-bot test Linux x64 Release Build please.

**Comment by harshjain2** [comment]
There seems to be something wrong with OpenSUSE Debug Build. Can anyone help here?

**Comment by harshjain2** [comment]
@dotnet-bot test this OpenSUSE42.1 x64 Debug Build please.

**Comment by harshjain2** [comment]
@dotnet-bot test OpenSUSE42.1 x64 Debug Build please.

**Comment by harshjain2** [comment]
cc @mlorbetske 
This PR is hanging around for long and OpenSUSE build is not finishing at all. Can you please help.

**Comment by harshjain2** [comment]
@dotnet-bot test this please.

**Comment by mlorbetske** [comment]
We should be OK to merge this. Either @seancpeters or I will take care of pushing it through in the morning

**Pull request merged**
