### PR TITLE
Testplatform 15.8 RTM insertion

### PR DESCRIPTION
**Pull request by abhishkk**
Release notes [here](https://github.com/Microsoft/vstest-docs/blob/master/docs/releases.md#1580).
VS insertion PR [here](https://devdiv.visualstudio.com/DevDiv/Automated%20Testing/_git/VS/pullrequest/131563?_a=overview).
Dot net CLI PR [here](https://github.com/dotnet/cli/pull/9645).

@mlorbetske Is stabilize right branch for VS 15.8 RTM?

### CODE REVIEW

**Comment by singhsarab** [comment]
@dotnet-bot test VSTS: macOS Build

**Comment by mlorbetske** [comment]
@abhishkk yes, all changes start at stabilize and flow to the release branch from there

@dotnet-bot test VSTS: macOS Build please

**Comment by mlorbetske** [comment]
@dotnet-bot test VSTS: macOS Build please

**Comment by mlorbetske** [comment]
@dotnet-bot test macOS Build please

**Pull request merged**
