### PR TITLE
Remove EOL openSuSE 42.1

### PR DESCRIPTION
**Pull request by mmitche**

### CODE REVIEW

**Comment by mmitche** [comment]
@dotnet-bot test ci please

**Comment by mmitche** [comment]
@mlorbetske Can you approve this?

**Comment by seancpeters** [comment]
@mlorbetske - I'm also not authorized for this branch. But I was able to merge into 3Preview-2. @mmitche was able to merge into master.

**Comment by mlorbetske** [comment]
I just made you an admin Sean. You may need to unlock the branch to be able to merge.

Thanks,
Mike

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Pull request merged**
