### PR TITLE
added dev/template-discovery to the list of auto-triggered CI builds

### PR DESCRIPTION
**Pull request by vlada-shubina**
added dev/template-discovery branch to the list of auto-triggered CI builds (temporarily, while we developing template discovery branch).

### CODE REVIEW

**Review by bozturkMSFT — APPROVED** [review]

**Review by DavidKarlas — APPROVED** [review]
I wonder if we should rename branch into `features/template-discovery` and put `features/*` here.. So in future we just name `features/tab-completion` and it will just work.

**Review by DavidKarlas — CHANGES_REQUESTED** [review]
I wonder if we should rename branch into `features/template-discovery` and put `features/*` here.. So in future we just name `features/tab-completion` and it will just work.
If you disagree with this idea, let me know, and I can approve this PR...

**Comment by vlada-shubina** [comment]
> I wonder if we should rename branch into `features/template-discovery` and put `features/*` here.. So in future we just name `features/tab-completion` and it will just work.
> If you disagree with this idea, let me know, and I can approve this PR...

I think dev/* is more of a standard, so I would prefer to put dev/* in this case.

**Comment by DavidKarlas** [comment]
I'm not fan of putting `dev/*` since that would include developers branches, like `dev/davkar/someBranch`, I would prefer if we use dedicated folder for big long running features branches...

**Review by DavidKarlas — APPROVED** [review]

**Pull request merged**
