### PR TITLE
Added WorkingDirectory property for #7471

### PR DESCRIPTION
**Pull request by egvijayanand**
### Problem

#7471 

### Solution

Added a property that returns the current directory (have named it `WorkingDirectory`) from where the dotnet command is invoked.

### Checks:
- [ ] Added unit tests

### CODE REVIEW

**Comment by baronfel** [comment]
Thank you! This is a great start, there are a few things that need to happen to get this green:

* the error from the CI systems is complaining about a missing signature in the PublicAPI files - this can be done via an analyzer in VS/VSCode
* Can you update the docs around the host-provided values [here](https://github.com/dotnet/templating/blob/main/docs/Binding-and-project-context-evaluation.md) as well?

**Comment by egvijayanand** [comment]
@baronfel I will check those feedback.

**Comment by egvijayanand** [comment]
@baronfel Have updated the advised details, can you review again and let me if anything more is to be done.

**Comment by baronfel** [comment]
This looks pretty good to me! There aren't tests for the existing built-ins, so as soon as you can fix the build error around the API surface area this should be good to merge :)

**Comment by egvijayanand** [comment]
> This looks pretty good to me! There aren't tests for the existing built-ins, so as soon as you can fix the build error around the API surface area this should be good to merge :)

This is the error message:

src\Microsoft.TemplateEngine.Edge\PublicAPI.Unshipped.txt(11,1): error RS0025: (NETCORE_ENGINEERING_TELEMETRY=Build) The symbol 'Microsoft.TemplateEngine.Edge.DefaultTemplateEngineHost.WorkingDirectory.get -> string!' **appears more than once in the public API files** (https://github.com/dotnet/roslyn-analyzers/blob/main/src/PublicApiAnalyzers/PublicApiAnalyzers.Help.md)

Should I remove these API details from the **Unshipped** file?

**Comment by baronfel** [comment]
It looks like the same line is present multiple times - so just removing the duplicates should be all that you need to do.

**Comment by egvijayanand** [comment]
> It looks like the same line is present multiple times - so just removing the duplicates should be all that you need to do.

It's not duplicated and only 11 items are present over there. That's why asking.

image

**Comment by egvijayanand** [comment]
After removing the entry from the Unshipped file, all checks have passed. Can you proceed with the merge?

**Comment by egvijayanand** [comment]
@baronfel can you look into this PR and let me know if anything else needs to be done?

**Review by baronfel — APPROVED** [review]
This LGTM - thanks for contributing. 

@MiYanni  / @joeloff - could one of you take a look from the engineering side?

**Review by MiYanni — APPROVED** [review]

**Comment by egvijayanand** [comment]
Hello @baronfel,

Can the PR be merged as the changes are approved?

**Comment by egvijayanand** [comment]
Thanks :-)

**Comment by egvijayanand** [comment]
@baronfel, From which .NET SDK version, this property will be made available?

**Comment by baronfel** [comment]
Either .NET SDK 9.0.100-preview.6 (last month's preview) or 9.0.100-preview.7 (this month's preview)

**Comment by egvijayanand** [comment]
> Either .NET SDK 9.0.100-preview.6 (last month's preview) or 9.0.100-preview.7 (this month's preview)

Ok thanks, will check.

**Pull request merged**
