### PR TITLE
Cache Blob Store Downloads

### PR DESCRIPTION
**Pull request by brianrob**
Prior to this change, every invocation of `dotnet new` downloaded a JSON document describing the list of available templates to ensure that all clients have an up-to-date template list.  With this PR, each invocation of `dotnet new` will do the following:
 - Only download the document if it has not been downloaded within the last hour.
 - If downloading the document, use If-None-Match and ETag headers to avoid downloading the actual document unless it is different than the local copy.  This avoids a usually redundant ~1MB download.

### CODE REVIEW

**Comment by brianrob** [comment]
cc: @KathleenDollard, @dsplaisted, @phenning, @donJoseLuis

**Comment by brianrob** [comment]
Any thoughts on this?  Thanks.

**Comment by phenning** [comment]
LGTM

**Comment by brianrob** [comment]
Thanks @phenning.  Anyone else have any comments or concerns?  I don't have merge permissions, so I'll be depending on y'all to merge this.

**Comment by brianrob** [comment]
Any other concerns on this one or can someone with permissions merge this?  Thanks.

**Comment by dsplaisted** [comment]
Looks like I don't have permissions either.  @phenning, do you have the write permissions to merge this?

**Comment by brianrob** [comment]
Thanks much @phenning!

**Pull request merged**
