### PR TITLE
Insert TestPlatform v15.0.0-preview-20170217-05.

### PR DESCRIPTION
**Pull request by smadala**
- Discovery is not getting triggered for project targeting net46 (issue [#375688](https://devdiv.visualstudio.com/DevDiv/VS.in%20Agile%20Testing%20IDE/_workitems?id=375688&_a=edit))
- Add TestContainer project capability and IsTestProject prop to Microsoft.Net.Test.Sdk.props (issue https://github.com/Microsoft/vstest/issues/394)
- Console output is badly formated (issue https://github.com/Microsoft/vstest/issues/478)
- Option to minimize console output on vstest.console (issue https://github.com/Microsoft/vstest/issues/301)

ASK mode template: Bug [386425](https://devdiv.visualstudio.com/DevDiv/VS.in%20Agile%20Testing%20IDE/_workitems?id=386425&fullScreen=false&_a=edit)

### CODE REVIEW

**Comment by smadala** [comment]
@livarcocc @sbaid @codito @piotrpMSFT @srivatsn

**Comment by mlorbetske** [comment]
@smadala changes look good, these will be coming through ship room today, right?

**Comment by mlorbetske** [comment]
Looks like ship room has approved, merging

**Comment by sbaid** [comment]
@smadala @mlorbetske  thanks. this payload is required for rtw & should be rel/vs2017/rtw this branch instead?

**Comment by sbaid** [comment]
@mlorbetske @smadala  looks like we are using this branch for the rtw templating work. then we are good. thanks!

**Comment by sbaid** [comment]
@bradwilson @onovotny

**Comment by mlorbetske** [comment]
rel/vs2017/rtw is for RTW engine work, rel/vs2017/post-rtw has the ongoing template work including the templates for RTW. We're hoping to move the templates out of this repo relatively soon to avoid more confusion on this

**Comment by bradwilson** [comment]
@sbaid I'm not sure why you tagged me.

**Comment by sbaid** [comment]
it was meant fyi.

**Pull request merged**
