### PR TITLE
Merging internal commits for release/6.0.1xx

### PR DESCRIPTION
**Pull request by vseanreesermsft**

### CODE REVIEW

**Review by vlada-shubina — APPROVED** [review]

**Comment by vlada-shubina** [comment]
@vseanreesermsft could you please resolve the conflicts?

**Comment by crummel** [comment]
I don't think there's any conflicts, at least GitHub isn't reporting any.  Could we get this merged to unblock the source-build release?

**Comment by crummel** [comment]
@vlada-shubina @vseanreesermsft This is blocking the public source-build PR for March (https://github.com/dotnet/source-build/pull/2788).  Could you please take a look soon?

**Comment by mmitche** [comment]
> @vlada-shubina @vseanreesermsft This is blocking the public source-build PR for March ([dotnet/source-build#2788](https://github.com/dotnet/source-build/pull/2788)). Could you please take a look soon?

@crummel Why does this block source build for March? The commits that make up this PR should be available in the repo due to the tagging procedure.

**Pull request merged**
