### PR TITLE
Simpify F# console app

### PR DESCRIPTION
**Pull request by dsyme**
### Problem

See https://github.com/dotnet/fsharp/issues/11883

### Solution

I am proposing to simplify the F# console app template, as described in the linked issue. This is the PR implementing the request

Marking as draft until fully discussed in dotnet/fsharp

The aka.ms link is currently going to https://docs.microsoft.com/en-us/dotnet/fsharp/, we will be writing new material specifically dealing with the issues mentioned in the issue linked above.

### CODE REVIEW

**Review by cartermp — APPROVED** [review]

**Comment by WhiteBlackGoose** [comment]
Shouldn't it have similar to C#'s compiler directive `csharpFeature_TopLevelProgram`? 😅

**Comment by vlada-shubina** [comment]
@dsyme @cartermp Could you also please check https://github.com/dotnet/templating/pull/3433 - community PR suggesting some changes? I assume we should close this one without merging, but giving some reasoning behind it will be nice. Thank you.

**Comment by vlada-shubina** [comment]
> Shouldn't it have similar to C#'s compiler directive `csharpFeature_TopLevelProgram`? 😅 

I'm not sure if it is applicable here. Having these directives in C# templates were caused by possibility of overriding language version via --langVersion option, which is not the case for F#.

**Comment by vlada-shubina** [comment]
@dsyme @cartermp Another concern - these changes will fly only to RC1 - are you ok with it? Isn't it too late?
Thanks

**Comment by dsyme** [comment]
> @dsyme @cartermp Another concern - these changes will fly only to RC1 - are you ok with it? Isn't it too late?

This is fine by us.

**Review by vlada-shubina — APPROVED** [review]

**Pull request merged**
