### PR TITLE
Update branding to preview3

### PR DESCRIPTION
**Pull request by phenning**

### CODE REVIEW

**Comment by vijayrkn** [comment]
@mmitche - Is it too late to update the branding? This is not critical if the build is already available.

**Comment by vijayrkn** [comment]
+@wtgodbe

**Comment by wtgodbe** [comment]
It's too late for preview3, we should just wait for the stabilization PR & include that in GA

**Comment by vijayrkn** [comment]
Sounds good. We never got to update to Preview 2 any ways. So this is not a big issue.

**Comment by jzabroski** [comment]
lol, "failing to follow semantic versioning is not a big deal"

**Comment by vijayrkn** [comment]
@jzabroski - There were absolutely no changes made in this repo after preview1 & also templating is not a .NET Core runtime component. That is the reason I mentioned this is not impactful. 

Hope this clarifies.

**Comment by jzabroski** [comment]
Ah, thank you.  Do you know if the upcoming dotnet repo merge into a mono-repo will allow a global MSBuild props file to contain this configuration, so that packages are released in a "global, build at head" fashion?  That seems like the appropriate solution.

**Pull request closed without merging**
