### PR TITLE
Updating test templates

### PR DESCRIPTION
**Pull request by singhsarab**
Updating the Microsoft.NET.Test.Sdk and MSTest adapter package reference in templates.

TestPlatform Release [v15.8.0-preview-20180605-02](https://github.com/Microsoft/vstest/releases/tag/v15.8.0-preview-20180605-02)
[Release Notes](https://github.com/Microsoft/vstest-docs/blob/master/docs/releases.md#1570)

MSTest Release [v1.3.1](https://github.com/Microsoft/testfx/releases/tag/v1.3.1)
[Release Notes](https://github.com/Microsoft/testfx-docs/blob/master/docs/releases.md#131-may-2018)

### CODE REVIEW

**Comment by singhsarab** [comment]
@jayaranigarg @smadala

**Comment by singhsarab** [comment]
@vijayrkn @mlorbetske Please let me know if this isn't the correct branch.

**Comment by mlorbetske** [comment]
@jayaranigarg has approval been gotten from the 15.8 quarterback?

@vijayrkn

**Comment by mlorbetske** [comment]
@singhsarab please follow up with @livarcocc and myself over e-mail about approval from the QB for insertion

**Pull request merged**
