### PR TITLE
Microsoft.NET.Test.Sdk 15.8.0-preview-20180510-03 insertion

### PR DESCRIPTION
**Pull request by abhishkk**
Microsoft.NET.Test.Sdk insertion for 15.8.0-preview-20180510-03

Release notes [here](https://github.com/Microsoft/vstest-docs/blob/master/docs/releases.md#1580-preview-20180510-03).
VS insertion PR [link](https://devdiv.visualstudio.com/DevDiv/Automated%20Testing/_git/VS/pullrequest/122154?_a=overview).

### CODE REVIEW

**Comment by abhishkk** [comment]
@mlorbetske Is release/2.1 right branch for VS 15.7 preview 2?

**Comment by mlorbetske** [comment]
Stabilize is the branch to use @vijayrkn @seancpeters

**Comment by seancpeters** [comment]
@mlorbetske - I'm currently working on getting stabilize, master, & release/2.1 into their proper states, then I'll rebase this (and the other template change PR) against stabilize.

**Comment by mlorbetske** [comment]
This looks to have been superseded by https://github.com/dotnet/templating/pull/1552/files

**Pull request closed without merging**
